package inf112.skeleton.app;

import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.Sprite;

import java.io.Serializable;
import java.util.Random;

// Enum representing card value
public enum CardValues implements Serializable {

     BACKUP430(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 430, "BACKUP")
    ,BACKUP432(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 432, "BACKUP")
    ,BACKUP434(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 434, "BACKUP")
    ,BACKUP436(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 436, "BACKUP")
    ,BACKUP438(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 438, "BACKUP")
    ,BACKUP440(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 440, "BACKUP")
    ,BACKUP442(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 442, "BACKUP")
    ,BACKUP444(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 444, "BACKUP")
    ,BACKUP446(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 446, "BACKUP")
    ,BACKUP448(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 448, "BACKUP")
    ,BACKUP450(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 450, "BACKUP")
    ,BACKUP452(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 452, "BACKUP")
    ,BACKUP454(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 454, "BACKUP")
    ,BACKUP456(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 456, "BACKUP")
    ,BACKUP458(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 458, "BACKUP")
    ,BACKUP460(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 460, "BACKUP")
    ,BACKUP462(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 462, "BACKUP")
    ,BACKUP464(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 464, "BACKUP")
    ,BACKUP466(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 466, "BACKUP")
    ,BACKUP468(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 468, "BACKUP")
    ,BACKUP470(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 470, "BACKUP")
    ,BACKUP472(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 472, "BACKUP")
    ,BACKUP474(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 474, "BACKUP")
    ,BACKUP476(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 476, "BACKUP")
    ,BACKUP478(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 478, "BACKUP")
    ,BACKUP480(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 480, "BACKUP")
    ,BACKUP482(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 482, "BACKUP")
    ,BACKUP484(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 484, "BACKUP")
    ,BACKUP486(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 486, "BACKUP")
    ,BACKUP488(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/BackUp.png")), 488, "BACKUP")



    ,MOVE1Pri490(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 490, "MOVE1")
    ,MOVE1Pri492(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 492, "MOVE1")
    ,MOVE1Pri494(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 494, "MOVE1")
    ,MOVE1Pri496(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 496, "MOVE1")
    ,MOVE1Pri498(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 498, "MOVE1")
    ,MOVE1Pri500(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 500, "MOVE1")
    ,MOVE1Pri502(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 502, "MOVE1")
    ,MOVE1Pri504(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 504, "MOVE1")
    ,MOVE1Pri506(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 506, "MOVE1")
    ,MOVE1Pri508(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 408, "MOVE1")
    ,MOVE1Pri510(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 410, "MOVE1")
    ,MOVE1Pri512(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 512, "MOVE1")
    ,MOVE1Pri514(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 514, "MOVE1")
    ,MOVE1Pri516(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 516, "MOVE1")
    ,MOVE1Pri518(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 518, "MOVE1")
    ,MOVE1Pri520(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 520, "MOVE1")
    ,MOVE1Pri522(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 522, "MOVE1")
    ,MOVE1Pri524(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 524, "MOVE1")
    ,MOVE1Pri526(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 526, "MOVE1")
    ,MOVE1Pri528(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 528, "MOVE1")
    ,MOVE1Pri530(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 530, "MOVE1")
    ,MOVE1Pri532(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 532, "MOVE1")
    ,MOVE1Pri534(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 534, "MOVE1")
    ,MOVE1Pri536(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 536, "MOVE1")
    ,MOVE1Pri538(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 538, "MOVE1")
    ,MOVE1Pri540(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 540, "MOVE1")
    ,MOVE1Pri542(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 542, "MOVE1")
    ,MOVE1Pri544(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 544, "MOVE1")
    ,MOVE1Pri546(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 546, "MOVE1")
    ,MOVE1Pri548(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 548, "MOVE1")
    ,MOVE1Pri550(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 550, "MOVE1")
    ,MOVE1Pri552(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 552, "MOVE1")
    ,MOVE1Pri554(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 554, "MOVE1")
    ,MOVE1Pri556(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 556, "MOVE1")
    ,MOVE1Pri558(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 558, "MOVE1")
    ,MOVE1Pri560(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 560, "MOVE1")
    ,MOVE1Pri562(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 562, "MOVE1")
    ,MOVE1Pri564(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 564, "MOVE1")
    ,MOVE1Pri566(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 566, "MOVE1")
    ,MOVE1Pri568(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 568, "MOVE1")
    ,MOVE1Pri570(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 570, "MOVE1")
    ,MOVE1Pri572(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 572, "MOVE1")
    ,MOVE1Pri574(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 574, "MOVE1")
    ,MOVE1Pri576(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 576, "MOVE1")
    ,MOVE1Pri578(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 578, "MOVE1")
    ,MOVE1Pri580(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 580, "MOVE1")
    ,MOVE1Pri582(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 582, "MOVE1")
    ,MOVE1Pri584(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 584, "MOVE1")
    ,MOVE1Pri586(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 586, "MOVE1")
    ,MOVE1Pri588(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 588, "MOVE1")
    ,MOVE1Pri590(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 590, "MOVE1")
    ,MOVE1Pri592(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 592, "MOVE1")
    ,MOVE1Pri594(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 594, "MOVE1")
    ,MOVE1Pri596(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 596, "MOVE1")
    ,MOVE1Pri598(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 598, "MOVE1")
    ,MOVE1Pri600(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 600, "MOVE1")
    ,MOVE1Pri602(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 602, "MOVE1")
    ,MOVE1Pri604(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 604, "MOVE1")
    ,MOVE1Pri606(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 606, "MOVE1")
    ,MOVE1Pri608(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 608, "MOVE1")
    ,MOVE1Pri610(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 610, "MOVE1")
    ,MOVE1Pri612(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 612, "MOVE1")
    ,MOVE1Pri614(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 614, "MOVE1")
    ,MOVE1Pri616(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 616, "MOVE1")
    ,MOVE1Pri618(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 618, "MOVE1")
    ,MOVE1Pri620(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 620, "MOVE1")
    ,MOVE1Pri622(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 622, "MOVE1")
    ,MOVE1Pri624(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 624, "MOVE1")
    ,MOVE1Pri626(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 626, "MOVE1")
    ,MOVE1Pri628(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 628, "MOVE1")
    ,MOVE1Pri630(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 630, "MOVE1")
    ,MOVE1Pri632(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 632, "MOVE1")
    ,MOVE1Pri634(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 634, "MOVE1")
    ,MOVE1Pri636(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 636, "MOVE1")
    ,MOVE1Pri638(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 638, "MOVE1")
    ,MOVE1Pri640(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 640, "MOVE1")
    ,MOVE1Pri642(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 642, "MOVE1")
    ,MOVE1Pri644(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 644, "MOVE1")
    ,MOVE1Pri646(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 646, "MOVE1")
    ,MOVE1Pri648(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 648, "MOVE1")
    ,MOVE1Pri650(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 650, "MOVE1")
    ,MOVE1Pri652(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 652, "MOVE1")
    ,MOVE1Pri654(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 654, "MOVE1")
    ,MOVE1Pri656(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 656, "MOVE1")
    ,MOVE1Pri658(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-1.png")), 658, "MOVE1")




    ,MOVE2pri670(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 670, "MOVE2")
    ,MOVE2pri672(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 672, "MOVE2")
    ,MOVE2pri674(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 674, "MOVE2")
    ,MOVE2pri676(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 676, "MOVE2")
    ,MOVE2pri678(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 678, "MOVE2")
    ,MOVE2pri680(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 680, "MOVE2")
    ,MOVE2pri682(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 682, "MOVE2")
    ,MOVE2pri684(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 684, "MOVE2")
    ,MOVE2pri686(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 686, "MOVE2")
    ,MOVE2pri688(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 688, "MOVE2")
    ,MOVE2pri690(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 690, "MOVE2")
    ,MOVE2pri692(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 692, "MOVE2")
    ,MOVE2pri694(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 694, "MOVE2")
    ,MOVE2pri696(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 696, "MOVE2")
    ,MOVE2pri698(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 698, "MOVE2")
    ,MOVE2pri700(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 700, "MOVE2")
    ,MOVE2pri702(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 702, "MOVE2")
    ,MOVE2pri704(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 704, "MOVE2")
    ,MOVE2pri706(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 706, "MOVE2")
    ,MOVE2pri708(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 708, "MOVE2")
    ,MOVE2pri710(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 710, "MOVE2")
    ,MOVE2pri712(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 712, "MOVE2")
    ,MOVE2pri714(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 714, "MOVE2")
    ,MOVE2pri716(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 716, "MOVE2")
    ,MOVE2pri718(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 718, "MOVE2")
    ,MOVE2pri720(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 720, "MOVE2")
    ,MOVE2pri722(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 722, "MOVE2")
    ,MOVE2pri724(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 724, "MOVE2")
    ,MOVE2pri726(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 726, "MOVE2")
    ,MOVE2pri728(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 728, "MOVE2")
    ,MOVE2pri730(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 730, "MOVE2")
    ,MOVE2pri732(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 732, "MOVE2")
    ,MOVE2pri734(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 734, "MOVE2")
    ,MOVE2pri736(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 736, "MOVE2")
    ,MOVE2pri738(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 738, "MOVE2")
    ,MOVE2pri740(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 740, "MOVE2")
    ,MOVE2pri742(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 742, "MOVE2")
    ,MOVE2pri744(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 744, "MOVE2")
    ,MOVE2pri746(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 746, "MOVE2")
    ,MOVE2pri748(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 748, "MOVE2")
    ,MOVE2pri750(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 750, "MOVE2")
    ,MOVE2pri752(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 752, "MOVE2")
    ,MOVE2pri754(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 754, "MOVE2")
    ,MOVE2pri756(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 756, "MOVE2")
    ,MOVE2pri758(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 758, "MOVE2")
    ,MOVE2pri760(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 760, "MOVE2")
    ,MOVE2pri762(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 762, "MOVE2")
    ,MOVE2pri764(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 764, "MOVE2")
    ,MOVE2pri766(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 766, "MOVE2")
    ,MOVE2pri768(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 768, "MOVE2")
    ,MOVE2pri770(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 770, "MOVE2")
    ,MOVE2pri772(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 772, "MOVE2")
    ,MOVE2pri774(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 774, "MOVE2")
    ,MOVE2pri776(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 776, "MOVE2")
    ,MOVE2pri778(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 778, "MOVE2")
    ,MOVE2pri780(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 780, "MOVE2")
    ,MOVE2pri782(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 782, "MOVE2")
    ,MOVE2pri784(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 784, "MOVE2")
    ,MOVE2pri786(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 786, "MOVE2")
    ,MOVE2pri788(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-2.png")), 788, "MOVE2")




    ,MOVE3pri790(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 790, "MOVE3")
    ,MOVE3pri792(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 792, "MOVE3")
    ,MOVE3pri794(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 794, "MOVE3")
    ,MOVE3pri796(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 796, "MOVE3")
    ,MOVE3pri798(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 798, "MOVE3")
    ,MOVE3pri800(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 800, "MOVE3")
    ,MOVE3pri802(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 802, "MOVE3")
    ,MOVE3pri804(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 804, "MOVE3")
    ,MOVE3pri806(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 806, "MOVE3")
    ,MOVE3pri808(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 808, "MOVE3")
    ,MOVE3pri810(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 810, "MOVE3")
    ,MOVE3pri812(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 812, "MOVE3")
    ,MOVE3pri814(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 814, "MOVE3")
    ,MOVE3pri816(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 816, "MOVE3")
    ,MOVE3pri818(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 818, "MOVE3")
    ,MOVE3pri820(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 820, "MOVE3")
    ,MOVE3pri822(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 822, "MOVE3")
    ,MOVE3pri824(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 824, "MOVE3")
    ,MOVE3pri826(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 826, "MOVE3")
    ,MOVE3pri828(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 828, "MOVE3")
    ,MOVE3pri830(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 830, "MOVE3")
    ,MOVE3pri832(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 832, "MOVE3")
    ,MOVE3pri834(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 834, "MOVE3")
    ,MOVE3pri836(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 836, "MOVE3")
    ,MOVE3pri838(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 838, "MOVE3")
    ,MOVE3pri840(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 840, "MOVE3")
    ,MOVE3pri842(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 842, "MOVE3")
    ,MOVE3pri844(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 844, "MOVE3")
    ,MOVE3pri846(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 846, "MOVE3")
    ,MOVE3pri848(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Move-3.png")), 848, "MOVE3")



    ,ROTATE90pri80(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 80, "ROTATE90")
    ,ROTATE90pri82(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 82, "ROTATE90")
    ,ROTATE90pri84(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 84, "ROTATE90")
    ,ROTATE90pri86(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 86, "ROTATE90")
    ,ROTATE90pri88(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 88, "ROTATE90")
    ,ROTATE90pri100(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 100, "ROTATE90")
    ,ROTATE90pri102(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 102, "ROTATE90")
    ,ROTATE90pri104(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 104, "ROTATE90")
    ,ROTATE90pri106(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 106, "ROTATE90")
    ,ROTATE90pri108(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 108, "ROTATE90")
    ,ROTATE90pri120(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 120, "ROTATE90")
    ,ROTATE90pri122(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 122, "ROTATE90")
    ,ROTATE90pri124(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 124, "ROTATE90")
    ,ROTATE90pri126(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 126, "ROTATE90")
    ,ROTATE90pri128(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 128, "ROTATE90")
    ,ROTATE90pri140(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 140, "ROTATE90")
    ,ROTATE90pri142(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 142, "ROTATE90")
    ,ROTATE90pri144(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 144, "ROTATE90")
    ,ROTATE90pri146(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 146, "ROTATE90")
    ,ROTATE90pri148(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 148, "ROTATE90")
    ,ROTATE90pri160(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 160, "ROTATE90")
    ,ROTATE90pri162(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 162, "ROTATE90")
    ,ROTATE90pri164(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 164, "ROTATE90")
    ,ROTATE90pri166(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 166, "ROTATE90")
    ,ROTATE90pri168(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 168, "ROTATE90")
    ,ROTATE90pri180(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 180, "ROTATE90")
    ,ROTATE90pri182(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 182, "ROTATE90")
    ,ROTATE90pri184(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 184, "ROTATE90")
    ,ROTATE90pri186(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 186, "ROTATE90")
    ,ROTATE90pri188(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 188, "ROTATE90")
    ,ROTATE90pri200(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 200, "ROTATE90")
    ,ROTATE90pri202(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 202, "ROTATE90")
    ,ROTATE90pri204(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 204, "ROTATE90")
    ,ROTATE90pri206(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 206, "ROTATE90")
    ,ROTATE90pri208(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 208, "ROTATE90")
    ,ROTATE90pri220(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 220, "ROTATE90")
    ,ROTATE90pri222(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 222, "ROTATE90")
    ,ROTATE90pri224(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 224, "ROTATE90")
    ,ROTATE90pri226(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 226, "ROTATE90")
    ,ROTATE90pri228(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 228, "ROTATE90")
    ,ROTATE90pri240(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 240, "ROTATE90")
    ,ROTATE90pri242(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 242, "ROTATE90")
    ,ROTATE90pri244(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 244, "ROTATE90")
    ,ROTATE90pri246(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 246, "ROTATE90")
    ,ROTATE90pri248(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 248, "ROTATE90")
    ,ROTATE90pri260(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 260, "ROTATE90")
    ,ROTATE90pri262(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 262, "ROTATE90")
    ,ROTATE90pri264(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 264, "ROTATE90")
    ,ROTATE90pri266(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 266, "ROTATE90")
    ,ROTATE90pri268(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 268, "ROTATE90")
    ,ROTATE90pri280(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 280, "ROTATE90")
    ,ROTATE90pri282(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 282, "ROTATE90")
    ,ROTATE90pri284(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 284, "ROTATE90")
    ,ROTATE90pri286(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 286, "ROTATE90")
    ,ROTATE90pri288(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 288, "ROTATE90")
    ,ROTATE90pri300(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 300, "ROTATE90")
    ,ROTATE90pri302(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 302, "ROTATE90")
    ,ROTATE90pri304(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 304, "ROTATE90")
    ,ROTATE90pri306(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 306, "ROTATE90")
    ,ROTATE90pri308(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 308, "ROTATE90")
    ,ROTATE90pri320(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 320, "ROTATE90")
    ,ROTATE90pri322(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 322, "ROTATE90")
    ,ROTATE90pri324(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 324, "ROTATE90")
    ,ROTATE90pri326(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 326, "ROTATE90")
    ,ROTATE90pri328(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 328, "ROTATE90")
    ,ROTATE90pri340(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 340, "ROTATE90")
    ,ROTATE90pri342(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 342, "ROTATE90")
    ,ROTATE90pri344(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 344, "ROTATE90")
    ,ROTATE90pri346(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 346, "ROTATE90")
    ,ROTATE90pri348(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 348, "ROTATE90")
    ,ROTATE90pri360(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 360, "ROTATE90")
    ,ROTATE90pri362(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 362, "ROTATE90")
    ,ROTATE90pri364(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 364, "ROTATE90")
    ,ROTATE90pri366(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 366, "ROTATE90")
    ,ROTATE90pri368(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 368, "ROTATE90")
    ,ROTATE90pri380(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 380, "ROTATE90")
    ,ROTATE90pri382(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 382, "ROTATE90")
    ,ROTATE90pri384(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 384, "ROTATE90")
    ,ROTATE90pri386(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 386, "ROTATE90")
    ,ROTATE90pri388(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 388, "ROTATE90")
    ,ROTATE90pri400(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 400, "ROTATE90")
    ,ROTATE90pri402(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 402, "ROTATE90")
    ,ROTATE90pri404(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 404, "ROTATE90")
    ,ROTATE90pri406(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 406, "ROTATE90")
    ,ROTATE90pri408(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 408, "ROTATE90")
    ,ROTATE90pri420(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 400, "ROTATE90")
    ,ROTATE90pri422(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 402, "ROTATE90")
    ,ROTATE90pri424(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 404, "ROTATE90")
    ,ROTATE90pri426(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 406, "ROTATE90")
    ,ROTATE90pri428(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-90.png")), 408, "ROTATE90")




    ,ROTATE180pri10(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 10, "ROTATE180")
    ,ROTATE180pri12(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 12, "ROTATE180")
    ,ROTATE180pri14(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 14, "ROTATE180")
    ,ROTATE180pri16(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 16, "ROTATE180")
    ,ROTATE180pri18(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 18, "ROTATE180")
    ,ROTATE180pri20(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 20, "ROTATE180")
    ,ROTATE180pri22(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 22, "ROTATE180")
    ,ROTATE180pri24(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 24, "ROTATE180")
    ,ROTATE180pri26(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 26, "ROTATE180")
    ,ROTATE180pri28(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 28, "ROTATE180")
    ,ROTATE180pri30(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 30, "ROTATE180")
    ,ROTATE180pri32(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 32, "ROTATE180")
    ,ROTATE180pri34(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 34, "ROTATE180")
    ,ROTATE180pri36(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 36, "ROTATE180")
    ,ROTATE180pri38(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 38, "ROTATE180")
    ,ROTATE180pri40(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 40, "ROTATE180")
    ,ROTATE180pri42(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 42, "ROTATE180")
    ,ROTATE180pri44(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 44, "ROTATE180")
    ,ROTATE180pri46(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 46, "ROTATE180")
    ,ROTATE180pri48(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 48, "ROTATE180")
    ,ROTATE180pri50(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 50, "ROTATE180")
    ,ROTATE180pri52(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 52, "ROTATE180")
    ,ROTATE180pri54(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 54, "ROTATE180")
    ,ROTATE180pri56(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 56, "ROTATE180")
    ,ROTATE180pri58(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 58, "ROTATE180")
    ,ROTATE180pri60(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 60, "ROTATE180")
    ,ROTATE180pri62(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 62, "ROTATE180")
    ,ROTATE180pri64(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 64, "ROTATE180")
    ,ROTATE180pri66(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 66, "ROTATE180")
    ,ROTATE180pri68(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-180.png")), 68, "ROTATE180")




    ,ROTATEC90pri70(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 70, "ROTATEC90")
    ,ROTATEC90pri72(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 72, "ROTATEC90")
    ,ROTATEC90pri74(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 74, "ROTATEC90")
    ,ROTATEC90pri76(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 76, "ROTATEC90")
    ,ROTATEC90pri78(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 78, "ROTATEC90")
    ,ROTATEC90pri90(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 90, "ROTATEC90")
    ,ROTATEC90pri92(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 92, "ROTATEC90")
    ,ROTATEC90pri94(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 94, "ROTATEC90")
    ,ROTATEC90pri96(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 96, "ROTATEC90")
    ,ROTATEC90pri98(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 98, "ROTATEC90")
    ,ROTATEC90pri110(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 110, "ROTATEC90")
    ,ROTATEC90pri112(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 112, "ROTATEC90")
    ,ROTATEC90pri114(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 114, "ROTATEC90")
    ,ROTATEC90pri116(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 116, "ROTATEC90")
    ,ROTATEC90pri118(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 118, "ROTATEC90")
    ,ROTATEC90pri130(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 130, "ROTATEC90")
    ,ROTATEC90pri132(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 132, "ROTATEC90")
    ,ROTATEC90pri134(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 134, "ROTATEC90")
    ,ROTATEC90pri136(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 136, "ROTATEC90")
    ,ROTATEC90pri138(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 138, "ROTATEC90")
    ,ROTATEC90pri150(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 150, "ROTATEC90")
    ,ROTATEC90pri152(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 152, "ROTATEC90")
    ,ROTATEC90pri154(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 154, "ROTATEC90")
    ,ROTATEC90pri156(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 156, "ROTATEC90")
    ,ROTATEC90pri158(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 158, "ROTATEC90")
    ,ROTATEC90pri170(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 170, "ROTATEC90")
    ,ROTATEC90pri172(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 172, "ROTATEC90")
    ,ROTATEC90pri174(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 174, "ROTATEC90")
    ,ROTATEC90pri176(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 176, "ROTATEC90")
    ,ROTATEC90pri178(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 178, "ROTATEC90")
    ,ROTATEC90pri190(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 190, "ROTATEC90")
    ,ROTATEC90pri192(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 192, "ROTATEC90")
    ,ROTATEC90pri194(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 194, "ROTATEC90")
    ,ROTATEC90pri196(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 196, "ROTATEC90")
    ,ROTATEC90pri198(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 198, "ROTATEC90")
    ,ROTATEC90pri210(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 210, "ROTATEC90")
    ,ROTATEC90pri212(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 212, "ROTATEC90")
    ,ROTATEC90pri214(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 214, "ROTATEC90")
    ,ROTATEC90pri216(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 216, "ROTATEC90")
    ,ROTATEC90pri218(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 218, "ROTATEC90")
    ,ROTATEC90pri230(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 230, "ROTATEC90")
    ,ROTATEC90pri232(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 232, "ROTATEC90")
    ,ROTATEC90pri234(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 234, "ROTATEC90")
    ,ROTATEC90pri236(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 236, "ROTATEC90")
    ,ROTATEC90pri238(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 238, "ROTATEC90")
    ,ROTATEC90pri250(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 250, "ROTATEC90")
    ,ROTATEC90pri252(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 252, "ROTATEC90")
    ,ROTATEC90pri254(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 254, "ROTATEC90")
    ,ROTATEC90pri256(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 256, "ROTATEC90")
    ,ROTATEC90pri258(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 258, "ROTATEC90")
    ,ROTATEC90pri270(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 270, "ROTATEC90")
    ,ROTATEC90pri272(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 272, "ROTATEC90")
    ,ROTATEC90pri274(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 274, "ROTATEC90")
    ,ROTATEC90pri276(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 276, "ROTATEC90")
    ,ROTATEC90pri278(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 278, "ROTATEC90")
    ,ROTATEC90pri290(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 290, "ROTATEC90")
    ,ROTATEC90pri292(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 292, "ROTATEC90")
    ,ROTATEC90pri294(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 294, "ROTATEC90")
    ,ROTATEC90pri296(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 296, "ROTATEC90")
    ,ROTATEC90pri298(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 298, "ROTATEC90")
    ,ROTATEC90pri310(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 310, "ROTATEC90")
    ,ROTATEC90pri312(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 312, "ROTATEC90")
    ,ROTATEC90pri314(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 314, "ROTATEC90")
    ,ROTATEC90pri316(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 316, "ROTATEC90")
    ,ROTATEC90pri318(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 318, "ROTATEC90")
    ,ROTATEC90pri330(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 330, "ROTATEC90")
    ,ROTATEC90pri332(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 332, "ROTATEC90")
    ,ROTATEC90pri334(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 334, "ROTATEC90")
    ,ROTATEC90pri336(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 336, "ROTATEC90")
    ,ROTATEC90pri338(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 338, "ROTATEC90")
    ,ROTATEC90pri350(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 350, "ROTATEC90")
    ,ROTATEC90pri352(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 352, "ROTATEC90")
    ,ROTATEC90pri354(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 354, "ROTATEC90")
    ,ROTATEC90pri356(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 356, "ROTATEC90")
    ,ROTATEC90pri358(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 358, "ROTATEC90")
    ,ROTATEC90pri370(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 370, "ROTATEC90")
    ,ROTATEC90pri372(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 372, "ROTATEC90")
    ,ROTATEC90pri374(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 374, "ROTATEC90")
    ,ROTATEC90pri376(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 376, "ROTATEC90")
    ,ROTATEC90pri378(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 378, "ROTATEC90")
    ,ROTATEC90pri390(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 390, "ROTATEC90")
    ,ROTATEC90pri392(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 392, "ROTATEC90")
    ,ROTATEC90pri394(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 394, "ROTATEC90")
    ,ROTATEC90pri396(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 396, "ROTATEC90")
    ,ROTATEC90pri398(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 398, "ROTATEC90")
    ,ROTATEC90pri410(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 410, "ROTATEC90")
    ,ROTATEC90pri412(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 412, "ROTATEC90")
    ,ROTATEC90pri414(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 414, "ROTATEC90")
    ,ROTATEC90pri416(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 416, "ROTATEC90")
    ,ROTATEC90pri418(new Sprite(new Texture("Models/AlleBevegelseKortUtenPrioritet/Rotate-C90.png")), 418, "ROTATEC90");


    private final Sprite spr;
    private final int priority;
    private final String name;

    CardValues(Sprite spr, int priority, String name){
        this.spr = spr;
        this.priority = priority;
        this.name = name;
    }

    public Sprite getSprite(){
        return spr;
    }

    public int getPriority() {
        return priority;
    }

    public String getName(){
        return name;
    }

    public static CardValues getRandomCard(){
        Random random = new Random();
        return CardValues.values()[random.nextInt(CardValues.values().length)];
    }

}
