@startuml

title __APP's Class Diagram__\n

  package inf112.skeleton.app {
    class CardsTest {
        ~ test : float
        + createCardTest()
        + createCardSlotTest()
        + createDeckTest()
        + addCardToDeckTest()
    }
  }
  

  package inf112.skeleton.app {
    class GridTest {
        + gridSetGetTest()
        + mapGetCellTest()
    }
  }
  

  package inf112.skeleton.app {
    class RobotTest {
        ~ posX : int
        ~ posY : int
        ~ startpos : int[]
        ~ random : Random
        ~ randInt : int
        ~ randBool : boolean
        + createRobotTest()
        + robotGettersSettersTest()
        + damageTest()
        + damageTest2()
        + damageTest3()
        + damageLivesTest()
        + damageLivesTest2()
        + damageLivesTest3()
        + robotSpinRightTest()
        + robotSpinLeftTest()
    }
  }
  

  package inf112.skeleton.app {
    class TestBot {
        + sprite : Sprite
        - alive : Boolean
        - posX : int
        - posY : int
        - checkpoint : int[]
        - flagsPassed : int
        - lives : int
        - damage : int
        - tilePixelWidth : int
        - tilePixelHeight : int
        - tiledMap : TiledMap
        - turn : int
        - powerdown : boolean
        + TestBot()
        + getAlive()
        + getPosX()
        + getPosY()
        + getSprite()
        + getCheckpoint()
        + getFlagsPassed()
        + getDirection()
        + getLives()
        + getDamage()
        + getTilePixelWidth()
        + getTilePixelHeight()
        + getPowerdown()
        + setPowerdown()
        + moveSprite()
        + rotateSprite()
        + setTurn()
        + setAlive()
        + setCheckpoint()
        + setFlagsPassed()
        + setDirection()
        + setPosX()
        + setPosY()
        + setDamage()
        + setLives()
        + rotate_right()
        + rotate_left()
        + moveForward()
        + move()
        + died()
        + takeDamage()
        + checkNext()
        + canMove()
    }
  }
  

  CardsTest o-- Cards : testCard
  CardsTest o-- CardSlots : testCardSlot
  CardsTest o-- Deck : deck
  RobotTest o-- IRobot : robot
  RobotTest o-- Direction : randDir
  TestBot -up-|> IRobot
  TestBot o-- CardHandler : cardHandler
  TestBot o-- Direction : dir
  TestBot o-- GameMap : gameMap
  TestBot o-- ExpressBelt : ebelt
  TestBot o-- Belt : belt
  TestBot o-- Spin : spin


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
