package map;
//enum for some of the different tile elements on the map
public enum MapTile {
    WALL, OPEN, PLAYER, MONSTER, FLAG, LASER, CONVEYERBELTNORTH,CONVEYERBELTSOUTH,CONVEYERBELTEAST,CONVEYERBELTWEST,EXPRESSCONVEYERBELT, GEAR, CHECKPOINT1, CHECKPOINT2, CHECKPOINT3, CHECKPOINT4, REPAIRSITE
}